---

#####################
# guest description #
#####################
node_prefix: ""
guest_os_distro: "{{ ansible_distribution | lower }}"
os_default_user: "{{ guest_os_distro }}"
guest_timezone: "UTC"

# Flatcar stuff
flatcar_update_server_ip: "11.102.100.1"
flatcar_update_server_port: 8000

nodes:
  - name: "controller1"
    type: "controller"
    cpu: 2
    ram: 8
    os_type: "centos"
    net_intfs:
      - name: "{{ net_prefix }}network-br"
      - name: "{{ net_prefix }}tunnel-br"
      - name: "{{ net_prefix }}ext-br"
  - name: "networknode1"
    type: "network_node"
    cpu: 2
    ram: 8
    os_type: "centos"
    net_intfs:
      - name: "{{ net_prefix }}network-br"
      - name: "{{ net_prefix }}tunnel-br"
      - name: "{{ net_prefix }}ext-br"
  - name: "compute1"
    type: "compute"
    cpu: 2
    ram: 8
    os_type: "centos"
    net_intfs:
      - name: "{{ net_prefix }}network-br"
      - name: "{{ net_prefix }}tunnel-br"
      - name: "{{ net_prefix }}ext-br"
  - name: "ceph"
    type: "ceph"
    cpu: 2
    ram: 4
    os_type: "centos"
    net_intfs:
      - name: "{{ net_prefix }}network-br"
      - name: "{{ net_prefix }}tunnel-br"
      - name: "{{ net_prefix }}ext-br"
    disks:
      - name: vol-osd1
        size: 40
        format: qcow2
      - name: vol-osd2
        size: 40
        format: qcow2
      - name: vol-osd3
        size: 40
        format: qcow2

# virt-customize
################
virt_customize_packages: []
virt_customize_cmd: []

# Networking
############
# First interface MUST be external one
net_prefix: ""

networks:
  - name: "{{ net_prefix }}network-br"
    forward: nat
    mode: dhcp
    cidr: "11.{{ net_second_octet | default(100) }}.100.0/24"
    pxe: False
  - name: "{{ net_prefix }}tunnel-br"
    mode: dhcp
    cidr: "11.{{ net_second_octet | default(100) }}.150.0/24"
  - name: "{{ net_prefix }}ext-br"
    mode: dhcp
    cidr: "11.{{ net_second_octet | default(100) }}.200.0/24"

host_ip: "{{ networks | selectattr('forward', 'defined') | selectattr('forward', 'equalto', 'nat') | map(attribute='cidr') | ipaddr('1') | ipaddr('address') | first }}"

# ip_offset [ 2-9 ]
# advanced use case to avoid IP conflict
#
# with ip_offset IP is define :
#   master node : 10 + ip_offset + outer_master_loop.index
#   woeker nide : 20 + ip_offset + outer_master_loop.index
ip_offset: 8

# Storage
#########
# in Go
root_disk_size: "80"

# Additional disks (LVM)
physical_disks:
  - /dev/nvme0n1p6
virt_volume_group: "virtvg"

# vm_volumes_mount: true
# vm_volumes_mount_path: "/data/kubernetes"

# Globals #
###########
home_dir: "{{ ansible_user_dir }}"
tmp_dir: "{{ home_dir}}/tmp"

############################
# Docker registry defaults #
############################
docker_enabled: "False"
docker_registry_ip: "{{ host_ip }}"
docker_registry_port: 5000
destroy_docker_registry: "False"
registry_enabled: "False"

############################
# Devpi PIP proxy defaults #
############################
pip_cache_enabled: "False"
destroy_pip_cache: "False"
pip_cache_proxy_ip: "{{ host_ip }}"
pip_cache_proxy_port: 3141

############################
# APT cache proxy defaults #
############################
apt_cache_enabled: "False"
destroy_apt_cache: "False"
apt_cache_proxy_ip: "{{ host_ip }}"
apt_cache_proxy_port: 3142

############################
#   DNS server defaults    #
############################
local_dns_enabled: "True"
dns_server_enabled: "False"
destroy_dns_server: "False"

dns_server_proxy_ip: "{{ host_ip }}"
dns_server_port: 53
dns_server_webproc_port: 5380
