---

#####################
# guest description #
#####################
node_prefix: ""
guest_os_distro: "{{ ansible_distribution | lower }}"
os_default_user: "{{ guest_os_distro }}"

# Cluster sizing
################
master_nb: 1
master_ram: 2
master_cpu: 2

worker_nb: 3
worker_ram: 4
worker_cpu: "{{ master_cpu }}"

# Networking
############
# First interface MUST be external one
net_prefix: "{{ node_prefix }}"

net_interfaces:
  - name: "{{ net_prefix }}ext-br"
    forward: nat
    mode: dhcp
    cidr: 10.0.100.0/24
    bridge: "{{ net_prefix }}ext-br"
    pxe: False
  - name: "{{ net_prefix }}overlay-br"
    mode: dhcp
    cidr: 10.0.150.0/24
    bridge: "{{ net_prefix }}overlay-br"

# Storage
#########
vm_volumes:
  - name: vol-osd
    size: 50
    format: qcow2

# Globals #
###########
home_dir: "{{ ansible_user_dir }}"
tmp_dir: "{{ home_dir}}/tmp"

############################
# Docker registry defaults #
############################
docker_enabled: "True"
docker_registry_ip: "{{ host_ip }}"
docker_registry_port: 5000
destroy_docker_registry: "False"

############################
# Devpi PIP proxy defaults #
############################
pip_cache_enabled: "False"
destroy_pip_cache: "False"
pip_cache_proxy_ip: "{{ host_ip }}"
pip_cache_proxy_port: 3141

############################
# APT cache proxy defaults #
############################
apt_cache_enabled: "False"
destroy_apt_cache: "False"
apt_cache_proxy_ip: "{{ host_ip }}"
apt_cache_proxy_port: 3142

############################
#   DNS server defaults    #
############################
local_dns_enabled: "True"
dns_server_enabled: "False"
destroy_dns_server: "False"

dns_server_proxy_ip: "{{ host_ip }}"
dns_server_port: 53
dns_server_webproc_port: 5380
