---
vm_os_distro: "{{ ansible_distribution | lower }}"
os_default_user: "{{ vm_os_distro }}"

config_owner_group: "kolla"
config_owner_user: "kolla"

############################
# Docker registry defaults #
############################
docker_enabled: "True"
docker_registry_ip: "{{ host_ip }}"
docker_registry_port: 5000
destroy_docker_registry: "False"

############################
# Devpi PIP proxy defaults #
############################
pip_cache_enabled: "False"
destroy_pip_cache: "False"
pip_cache_proxy_ip: "{{ host_ip }}"
pip_cache_proxy_port: 3141

############################
# APT cache proxy defaults #
############################
apt_cache_enabled: "False"
destroy_apt_cache: "False"
apt_cache_proxy_ip: "{{ host_ip }}"
apt_cache_proxy_port: 3142

############################
#   DNS server defaults    #
############################
libvirt_dns_enabled: "True"
dns_server_enabled: "False"
destroy_dns_server: "False"

dns_server_proxy_ip: "{{ host_ip }}"
dns_server_port: 53
dns_server_webproc_port: 5380
