---

#####################
# guest description #
#####################
node_prefix: ""
guest_os_distro: "{{ ansible_distribution | lower }}"
os_default_user: "{{ guest_os_distro }}"

# Flatcar stuff
flatcar_update_server_ip: "11.102.100.1"
flatcar_update_server_port: 8000

# Cluster sizing
################
master_nb: 1
master_ram: 2
master_cpu: 2

worker_nb: 1
worker_ram: 1
worker_cpu: "{{ master_cpu }}"

lb_nb: 2
lb_ram: 1
lb_cpu: 1

node_type_os:
  - type: "lb"
    os: "debian"
  - type: "worker"
    os: "{{ guest_os_distro }}"
  - type: "master"
    os: "{{ guest_os_distro }}"

# virt-customize
################
virt_customize_packages: []
virt_customize_cmd: []

# Networking
############
# First interface MUST be external one
net_prefix: "{{ node_prefix }}"
net_second_octet: "{{ net_second_octet | default(100) }}"

net_interfaces:
  - name: "{{ net_prefix }}net-br"
    forward: nat
    mode: dhcp
    cidr: "11.{{ net_second_octet }}.100.0/24"
    bridge: "{{ net_prefix }}net-br"
    pxe: False
  - name: "{{ net_prefix }}over-br"
    mode: dhcp
    cidr: "11.{{ net_second_octet }}.150.0/24"
    bridge: "{{ net_prefix }}over-br"
  # - name: "{{ net_prefix }}pub-br"
  #   mode: static
  #   cidr: "11.{{ net_second_octet }}.200.0/24"
  #   bridge: "{{ net_prefix }}pub-br"
  # - name: "{{ net_prefix }}clust-br"
  #   mode: static
  #   cidr: "11.{{ net_second_octet }}.210.0/24"
  #   bridge: "{{ net_prefix }}clust-br"

# Storage
#########
vm_volumes: []
# vm_volumes:
#   - name: vol-osd1
#     size: 10
#     format: qcow2
#   - name: vol-osd2
#     size: 10
#     format: qcow2
#   - name: vol-osd3
#     size: 10
#     format: qcow2
#   - name: vol-osd4
#     size: 10
#     format: qcow2
# vm_volumes_mount: True
# vm_volumes_mount_path: "/data/s3"

# Storage
#########
root_disk_size: "100"

# Additional disks (LVM)
physical_disks:
  - /dev/nvme0n1p6
virt_volume_group: "virtvg"

# Globals #
###########
home_dir: "{{ ansible_user_dir }}"
tmp_dir: "{{ home_dir}}/tmp"

############################
# Docker registry defaults #
############################
docker_enabled: "True"
docker_registry_ip: "{{ host_ip }}"
docker_registry_port: 5000
destroy_docker_registry: "False"
registry_enabled: "False"

############################
# Devpi PIP proxy defaults #
############################
pip_cache_enabled: "False"
destroy_pip_cache: "False"
pip_cache_proxy_ip: "{{ host_ip }}"
pip_cache_proxy_port: 3141

############################
# APT cache proxy defaults #
############################
apt_cache_enabled: "False"
destroy_apt_cache: "False"
apt_cache_proxy_ip: "{{ host_ip }}"
apt_cache_proxy_port: 3142

############################
#   DNS server defaults    #
############################
local_dns_enabled: "True"
dns_server_enabled: "False"
destroy_dns_server: "False"

dns_server_proxy_ip: "{{ host_ip }}"
dns_server_port: 53
dns_server_webproc_port: 5380
