---

host_ip: "{{ net_interfaces | selectattr('forward', 'defined') | selectattr('forward', 'equalto', 'nat') | map(attribute='cidr') | ipaddr('1') | ipaddr('address') | first }}"
dns_domain: "mydomain.org"

# to install libvirt stuff in guest vm set to True
allow_virt: False

# # kubernetes
# ############
# cni_version: v0.8.6
# kubernetes_version: v1.18.8
# crictl_version: v1.18.0
# setup_command: "kubeadm init --config=/etc/kubernetes/kubeadm-custom-config.yaml"
# pod_subnet: "10.244.0.0/16"
# kube_binaries_path: "/usr/local/bin"
