---
###########
# Globals #
###########
home_dir: "{{ ansible_user_dir }}"
tmp_dir: "{{ home_dir}}/tmp"
libvirt_dir: "/var/lib/libvirt/images"

#####################
# Docker containers #
#####################
docker_registry_name: "registry"
docker_registry_image: "registry:2"

docker_pip_cache_name: "devpi_proxy"
docker_pip_cache_image: "127.0.0.1:5000/devpi"

docker_apt_cache_name: "apt-cacher-ng_proxy"
docker_apt_cache_image: "127.0.0.1:5000/apt-cacher-ng"

docker_dns_server_name: "docker-dnsmasq"
docker_dns_server_image: "127.0.0.1:5000/docker-dnsmasq"

############
# Packages #
############
yum_dependencies:
  - libvirt
  - libvirt-devel
  - bridge-utils
  - genisoimage
  - python-requests
  - qemu-kvm

apt_dependencies:
  - openssh-server
  - libvirt-bin
  - bridge-utils
  - genisoimage
  - python-requests
  - qemu-kvm

pip_dependencies:
  - docker
  - libvirt-python
  - lxml
  - pip

destroy_images: False

#vm_os_image: "ubuntu-16.04-server-cloudimg-amd64-disk1.img"
#vm_os_image: "CentOS-7-x86_64-GenericCloud.qcow2"
vm_os_image: "debian-10-openstack-amd64.qcow2"

os_default_user: "{{ vm_os_distro }}"
