---

host_ip: "{{ net_interfaces | selectattr('forward', 'defined') | selectattr('forward', 'equalto', 'nat') | map(attribute='cidr') | ipaddr('1') | ipaddr('address') | first }}"
dns_domain: "mydomain.org"

# Storage
#########
root_disk_size: "50"
# Additional disks (LVM)
physical_disks:
  - /dev/nvme0n1p6
virt_volume_group: "virtvg"

vm_volumes:
  - name: vol-osd
    size: 50
    format: raw

# # kubernetes
# ############
# cni_version: v0.8.6
# kubernetes_version: v1.18.8
# crictl_version: v1.18.0
# setup_command: "kubeadm init --config=/etc/kubernetes/kubeadm-custom-config.yaml"
# pod_subnet: "10.244.0.0/16"
# kube_binaries_path: "/usr/local/bin"
