---
node_prefix: ""

# Cluster sizing info
#####################
master_nb: 1
master_ram: 4
master_cpu: 2

worker_nb: 1
worker_ram: "{{ master_ram }}"
worker_cpu: "{{ master_cpu }}"

# Networking
############
net_interfaces:
  - name: overlay-br
    mode: dhcp
    cidr: 10.150.150.0/24
    bridge: overlay-br
  - name: ext-br
    forward: nat
    mode: dhcp
    cidr: 10.100.100.0/24
    bridge: ext-br
    pxe: True

dns_domain: "mydomain.org"

# Storage
#########
root_disk_size: "20"
# Additional disks (LVM)
physical_disks:
  - /dev/nvme0n1p6
virt_volume_group: "virtvg"

vm_volumes: []
  # - name: vol1
  #   size: 20
  #   format: raw
  # - name: vol2
  #   size: 20
  #   format: raw

# # kubernetes
# ############
# cni_version: v0.8.6
# kubernetes_version: v1.18.8
# crictl_version: v1.18.0
# setup_command: "kubeadm init --config=/etc/kubernetes/kubeadm-custom-config.yaml"
# pod_subnet: "10.244.0.0/16"
# kube_binaries_path: "/usr/local/bin"
