#!/bin/bash

NODE_PREFIX=""
SERVICES="${NODE_PREFIX}master* ${NODE_PREFIX}worker*"
SNAPSHOT_NAME=""
TIMEOUT=300

function start {
#    docker start docker-dnsmasq
	list_inactive_domains | while read DOMAIN; do
        for service in $SERVICES; do
            if [[ "$DOMAIN" =~ $service ]]; then
		        virsh start $DOMAIN
            fi
        done
	done
}

function destroy {
	list_all_domains | while read DOMAIN; do
        for service in $SERVICES; do
            if [[ "$DOMAIN" =~ $service ]]; then
                virsh destroy $DOMAIN
		        virsh undefine --remove-all-storage $DOMAIN
            fi
        done
	done
}

function list_inactive_domains() {
    virsh -q list --inactive | grep "shut off" | awk '{print $2}'
}

function list_running_domains() {
    virsh -q list | grep "running" | awk '{ print $2}'
}

function list_all_domains() {
    virsh -q list | awk '{ print $2}'
}

function gracefully_shutdown {
	echo -e "Try to cleanly shut down all running KVM domains...\n"

	# Try to shutdown each domain, one by one.
	list_running_domains | while read DOMAIN; do
		# Try to shutdown given domain.
		virsh shutdown $DOMAIN --mode acpi
	done

	# Wait until all domains are shut down or timeout has reached.
	END_TIME=$(date -d "$TIMEOUT seconds" +%s)

	while [ $(date +%s) -lt $END_TIME ]; do
		# Break while loop when no domains are left.
		test -z "$(list_running_domains)" && break
		# Wait a litte, we don't want to DoS libvirt.
		sleep 1
	done

	# Clean up left over domains, one by one.
	list_running_domains | while read DOMAIN; do
		# Try to shutdown given domain.
		virsh destroy $DOMAIN
		# Give libvirt some time for killing off the domain.
		sleep 3
	done
}

function snap-create {
    gracefully_shutdown
	list_inactive_domains | while read DOMAIN; do
        for service in $SERVICES; do
            if [[ "$DOMAIN" =~ $service ]]; then
                virsh snapshot-create-as --domain $DOMAIN --name $SNAPSHOT_NAME
                echo "Snapshot $SNAPSHOT_NAME create for domain $DOMAIN"
            fi
        done
    done
    start
}

function snap-delete {
    gracefully_shutdown
	list_inactive_domains | while read DOMAIN; do
        for service in $SERVICES; do
            if [[ "$DOMAIN" =~ $service ]]; then
                virsh snapshot-delete $DOMAIN --snapshotname $SNAPSHOT_NAME
                echo "Snapshot $SNAPSHOT_NAME remove for domain $DOMAIN"
            fi
        done
    done
    start
}

function snap-revert {
    gracefully_shutdown
	list_inactive_domains | while read DOMAIN; do
        for service in $SERVICES; do
            if [[ "$DOMAIN" =~ $service ]]; then
                virsh snapshot-revert $DOMAIN --snapshotname $SNAPSHOT_NAME
                echo "Snapshot $SNAPSHOT_NAME revert for domain $DOMAIN"
            fi
        done
    done
    start
}

function snap-list {
	list_all_domains | while read DOMAIN; do
        for service in $SERVICES; do
            if [[ "$DOMAIN" =~ $service ]]; then
                virsh -q snapshot-list --domain $DOMAIN
            fi
        done
    done
}

function usage {
    cat <<EOF
Usage: $0 COMMAND

Commands:
    --cleanup                        Cleanup (destroy & undefine) cluster
    --start                          Start cluster
    --shutdown                       Shutdown cluster
    --snap-create <snapshot name>    Create cluster snapshot
    --snap-delete <snapshot name>    Delete cluster snapshot
    --snap-revert <snapshot name>    Revert cluster snapshot
    --snap-list                      List cluster snapshots
EOF
}

LONG_OPTS="purge,start,shutdown,snap-delete:,snap-create:,snap-revert:,snap-list,help"
ARGS=$(getopt -l "${LONG_OPTS}" --name "$0" -- "$@") || { usage >&2; exit 2; }

while [ "$#" -gt 0 ]; do
    case "$1" in
    (--purge)
        destroy
        undefine
        exit 0
        ;;
    (--start)
        start
        exit 0
        ;;
    (--shutdown)
        gracefully_shutdown
        exit 0
        ;;
    (--snap-delete)
        SNAPSHOT_NAME=$2
        shift 2
        snap-delete
        exit 0
        ;;
    (--snap-create)
        SNAPSHOT_NAME=$2
        shift 2
        snap-create
        exit 0
        ;;
    (--snap-revert)
        SNAPSHOT_NAME=$2
        shift 2
        snap-revert
        exit 0
        ;;
    (--snap-list)
        snap-list
        exit 0
        ;;
    (--help|-h)
        usage
        exit 0
        ;;
    (*)
        usage
        exit 3
        ;;
esac
done
