---
- name: Load cluster_nodes variables
  set_fact:
    cluster_nodes: "{{ lookup('template','nodes.j2') | from_yaml }}"

# TODO(bl) destroy snapshots if present
- name: Steps to destroy containers
  block:
    - name: Delete containers
      lxd_container:
        name: "{{ item.name }}"
        state: absent
        snap_url: "{{ lxd_snap_url }}"
      with_items: "{{ cluster_nodes }}"

# - import_tasks: lxd/destroy_networks.yml
- import_tasks: libvirt/destroy_networks.yml
  when: networks | length > 0
  tags: network

- include_tasks: lxd/destroy_disks.yml

- name: "Clean nodes config in {{ tmp_dir }}"
  file:
    path: "{{ tmp_dir }}/{{ item.name }}"
    state: absent
  with_items: "{{ cluster_nodes }}"

- name: Clean nodes from ssh_config
  become: True
  blockinfile:
    block: "{{ lookup('template', 'ssh_config.j2') }}"
    path: "{{ ansible_env.HOME }}/.ssh/config"
    state: absent
  ignore_errors: True

- name: Clean /etc/hosts file
  become: True
  lineinfile:
    path: /etc/hosts
    line: "{{ item.1.address }} {{ item.0.name }}.{{ dns_domain }} {{ item.0.name }}"
    state: absent
  with_subelements:
    - "{{ cluster_nodes }}"
    - interfaces
  when: item.1.address is defined and item.1.external is defined and item.1.external
  ignore_errors: True

- name: "Clean {{ ansible_env.HOME }}/.ssh/known_hosts"
  known_hosts:
    path: "{{ ansible_env.HOME }}/.ssh/known_hosts"
    name: "{{ item.name }}.{{ dns_domain }}"
    state: absent
  with_items: "{{ cluster_nodes }}"
  ignore_errors: True
