---
- name: Check storage is available
  block:
    - name: Check physical_disks is set
      fail:
        msg: "when vm_volumes|length > 0, physical_disks MUST be set"
      when: physical_disks is not defined

    - name: List storage pool
      community.libvirt.virt_pool:
        command: list_pools
      register: pool_exists

    - name: "Define {{ virt_volume_group }} storage pool"
      become: true
      community.libvirt.virt_pool:
        command: define
        name: "{{ virt_volume_group }}"
        xml: "{{ lookup('template', 'libvirt/pool.xml.j2') }}"
      when: virt_volume_group not in pool_exists.list_pools

    - name: Copy Libvirt XML pool domain in {{ tmp_dir }}/pool.xml
      blockinfile:
        path: "{{ tmp_dir }}/pool.xml"
        create: true
        block: |
          {{ lookup('template', 'libvirt/pool.xml.j2') }}

    - name: "Start {{ virt_volume_group }} storage pool"
      become: true
      community.libvirt.virt_pool:
        command: create
        name: "{{ virt_volume_group }}"
      when: virt_volume_group not in pool_exists.list_pools

    - name: "Autostart {{ virt_volume_group }} storage pool"
      become: true
      community.libvirt.virt_pool:
        autostart: true
        name: "{{ virt_volume_group }}"

  when: vm_volumes|length > 0
