---

host_ip: "{{ networks | selectattr('forward', 'defined') | selectattr('forward', 'equalto', 'nat') | map(attribute='cidr') | ipaddr('1') | ipaddr('address') | first }}"
dns_domain: "mydomain.org"

# to install libvirt stuff in guest set to True
allow_virt: False

# Storage
#########
root_disk_size: "50"
# Additional disks (LVM)
physical_disks:
  - /dev/nvme0n1p6
virt_volume_group: "virtvg"

# vm_volumes:
#   - name: vol-osd
#     size: 50
#     format: raw
