---
- name: Build PIP cache proxy image and push it
  docker_image:
    name: "{{ docker_pip_cache_image }}"
    path: roles/virtual_nodes/tasks/docker/proxy/pip
    dockerfile: Dockerfile
    push: True

- name: Create a PIP cache proxy
  docker_container:
    name: "{{ docker_pip_cache_name }}"
    image: "{{ docker_pip_cache_image }}"
    restart_policy: unless-stopped
    published_ports:
      - "{{ pip_cache_proxy_ip }}:{{ pip_cache_proxy_port }}:3141"
    volumes:
      - "devpi:/var/lib/devpi"

- name: Wait for PIP cache proxy ready
  wait_for:
    host: "{{ pip_cache_proxy_ip }}"
    port: "{{ pip_cache_proxy_port }}"
    delay: 10
    timeout: 250
