---
- name: Build APT cache proxy image and push it
  docker_image:
    name: "{{ docker_apt_cache_image }}"
    source: build
    build:
      path: roles/virtual_nodes/tasks/docker/proxy/apt
      dockerfile: Dockerfile
      pull: False
    push: True

- name: Create a APT cache proxy
  docker_container:
    name: "{{ docker_apt_cache_name }}"
    image: "{{ docker_apt_cache_image }}"
    restart_policy: unless-stopped
    published_ports:
      - "{{ apt_cache_proxy_ip }}:{{ apt_cache_proxy_port }}:3142"
    volumes:
      - "apt-cacher-ng:/var/cache/apt-cacher-ng"

- name: Wait for APT cache proxy ready
  wait_for:
    host: "{{ apt_cache_proxy_ip }}"
    port: "{{ apt_cache_proxy_port }}"
    delay: 10
    timeout: 250
