---
- name: Create a local Docker registry
  docker_container:
    name: "{{ docker_registry_name }}"
    image: "{{ docker_registry_image }}"
    restart_policy: unless-stopped
    published_ports:
      - "5000:5000"
    volumes:
      - "registry:/var/lib/registry"
