---
#############################
# Kolla passwords overrides #
#############################
password_overrides:
  database_password: admin
  grafana_admin_password: admin
  haproxy_password: admin
  keystone_admin_password: admin
  kibana_password: admin
  osprofiler_secret: admin
  rabbitmq_password: guest

###############################
# Kolla globals.yml overrides #
###############################
globals_override:
  # api_interface: ""

  # timedatectl sees the system clock as unsynchronized.
  # Please wait for synchronization.
  # Alternatively, set 'prechecks_enable_host_ntp_checks' to 'false'
  # to disable this check if your NTP daemon is not recognised by 'timedatectl status'
  prechecks_enable_host_ntp_checks: false

  # this provides the required default for other interfaces below.
  network_interface: "{{ network_intf }}"
  #  This interface is used for the management network.
  # The management network is the network OpenStack services uses
  # to communicate to each other and the databases.
  # There are known security risks here, so it’s recommended to make
  # this network internal, not accessible from outside.
  # Defaults to network_interface.
  api_interface: "{{ network_intf }}"
  # This interface is used by Neutron for vm-to-vm traffic over tunneled networks (like VxLan).
  # Defaults to network_interface.
  tunnel_interface: "{{ tunnel_intf }}"
  neutron_bridge_name: "{{ neutron_ext_bridges | default('br-ex') }}"
  # This interface is required by Neutron. Neutron will put br-ex on it.
  # It will be used for flat networking as well as tagged vlan networks.
  neutron_external_interface: "{{ external_intfs }}"
  kolla_install_type: "source"
  kolla_base_distro: "{{ vm_os_distro }}"
  kolla_dev_mode: "{{ kolla_dev_mode }}"
  kolla_config_path: "{{ kolla_config_path }}"
#  docker_registry: "{{ docker_registry_ip }}:{{ docker_registry_port }}"
#  docker_namespace: "{{ kolla_image_namespace }}"
  kolla_internal_vip_address: "11.101.100.11"
#  kolla_external_vip_address: "11.101.100.21"

  # Enable core OpenStack services. This includes:
  # glance, keystone, neutron, nova, heat, and horizon.
  enable_openstack_core: "yes"

  enable_glance: "yes"

  enable_haproxy: "no"
  enable_keepalived: "no"

  enable_loadbalancer: "no"
  enable_keystone: "yes"
  enable_keystone_federation: "no"
  enable_mariadb: "yes"
  enable_memcached: "yes"
  enable_neutron: "yes"
#  enable_neutron_agent_ha: "yes"
  enable_neutron_provider_networks: "yes"
  enable_nova: "yes"
  enable_rabbitmq: "yes"
  enable_outward_rabbitmq: "no"

  # NOTE: Most memcached clients handle load-balancing via client side
  # hashing (consistent or not) logic, so going under the covers and messing
  # with things that the clients are not aware of is generally wrong
  enable_haproxy_memcached: "no"

  # Additional optional OpenStack features and services are specified here
  enable_aodh: "no"
  enable_barbican: "no"
  enable_blazar: "no"
  enable_ceilometer: "no"
  enable_ceilometer_ipmi: "no"
  enable_cells: "no"

  enable_fluentd: "no"
  enable_central_logging: "no"
  elasticsearch_datadir_volume: "/logs"

  enable_elasticsearch_curator: "no"
  enable_ceph_rgw: "no"
  enable_ceph_rgw_loadbalancer: "no"
  enable_cinder: "yes"
  enable_cinder_backup: "no"
  enable_cinder_backend_hnas_nfs: "no"
  enable_cinder_backend_iscsi: "no"
  enable_cinder_backend_lvm: "no"
  enable_cinder_backend_nfs: "no"
  enable_cinder_backend_quobyte: "no"
  enable_cloudkitty: "no"
  enable_collectd: "no"
  enable_cyborg: "no"
  enable_designate: "yes"
  enable_horizon_designate: "yes"

  enable_osprofiler: "yes"
  enable_elasticsearch: "yes"

  enable_etcd: "no"
  enable_freezer: "no"
  enable_gnocchi: "no"
  enable_gnocchi_statsd: "no"
  enable_grafana: "no"
  enable_hacluster: "no"
  enable_heat: "no"
  enable_horizon: "yes"
  enable_prometheus: "no"
  enable_prometheus_openstack_exporter: "no"
  # Ceph
  glance_backend_ceph: "no"
  glance_backend_s3: "yes"
  # ceph_glance_keyring: "ceph.client.glance.keyring"
  # ceph_glance_user: "glance"
  # ceph_glance_pool_name: "images"

  nova_backend_ceph: "yes"
  ceph_nova_keyring: "ceph.client.cinder.keyring"
  ceph_nova_user: "cinder"
  ceph_nova_pool_name: "vms"

  cinder_backend_ceph: "yes"
  cinder_backup_driver: "s3"

  ceph_cinder_keyring: "ceph.client.cinder.keyring"
  ceph_cinder_user: "cinder"
  ceph_cinder_pool_name: "volumes"
  ceph_cinder_backup_keyring: "ceph.client.cinder-backup.keyring"
  ceph_cinder_backup_user: "cinder-backup"
  ceph_cinder_backup_pool_name: "backups"

  dns_interface: "eth0"
  designate_backend: "bind9"
  designate_ns_record: "ns1.clovis.thales.org"
  designate_dns_domain: "default.clovis.thales.org."

  neutron_dnsmasq_dns_servers: "11.101.100.11"

#######################
# Inventory overrides #
#######################
inventory_override:
  control01: controller1
  control02: ''
  control03: ''
  network01: networknode1
  network02: ''
  monitoring01: controller1
  storage01: networknode1
  compute01: compute1

#####################
# Kolla host defaults
#####################
tmp_dir: "/tmp"
kolla_node_home_dir: "{{ ansible_user_dir }}"
kolla_venv_path: "/home/centos/venv"
kolla_ansible_repo: "https://github.com/blallau/kolla-ansible"
kolla_ansible_branch: "stable/xena"
