---
- name: Create default LXD storage
  ansible.builtin.shell: >
    {{ lxd_bin_folder }}/lxc storage create default dir
    source=/var/snap/lxd/common/lxd/storage-pools/default
  register: default_storage_add
  changed_when: "default_storage_add.rc == 0"
  failed_when:
    - "default_storage_add.rc != 0"
    - "'already exists' not in default_storage_add.stderr"
  args:
    executable: /bin/bash
...
