---
- name: Prepare nodes
  hosts: nodes
  become: True
  tasks:
    - name: Install packages
      apt:
        pkg:
          - drbd-utils
          - lvm2
      when: ansible_distribution|lower in ["ubuntu", "debian"]

    - name: Install packages
      yum:
        name:
          - drbd
          - kmod-drbd
          - lvm2
        update_cache: True
      when: ansible_distribution|lower == "centos"

    - name: Load drbd kernel module
      modprobe:
        name: drbd
        state: absent

    - name: Enable drbd module
      lineinfile:
        path: /etc/modules-load.d/drbd.conf
        line: 'drbd'
        create: True

- name: Deploy linstor controller
  hosts: master
  become: True
  tasks:
    - name: Install Ubuntu packages
      apt:
        pkg:
          - linstor-controller
          - linstor-satellite
          - linstor-client
      when: ansible_distribution|lower in ["ubuntu", "debian"]

    - name: Install packages
      yum:
        name:
          - linstor-controller
          - linstor-satellite
          - linstor-client
        update_cache: True
      when: ansible_distribution|lower == "centos"

    - name: Start linstor-controller controller
      systemd:
        name: "linstor-controller"
        enabled: yes
        state: restarted

- name: Deploy linstor satellite
  hosts: nodes
  become: True
  tasks:
    - name: Install Ubuntu packages
      apt:
        pkg:
          - linstor-satellite
          - linstor-client
      when: ansible_distribution|lower in ["ubuntu", "debian"]

    - name: Install packages
      yum:
        name:
          - linstor-satellite
          - linstor-client
        update_cache: True
      when: ansible_distribution|lower == "centos"

    - name: Start linstor-controller controller
      systemd:
        name: "linstor-satellite"
        enabled: yes
        state: restarted
