---
############
# Packages #
############
yum_dependencies:
  - snap
  - pkgconfig
  - libvirt-dev

apt_dependencies:
  - snap
  - pkg-config
  - libvirt-dev
  - libvirt-daemon-system
  - libvirt-clients

pip_dependencies:
  - requests
  - libvirt-python
  - netaddr
  - lxml

#############
# OS images #
#############
container_os_images:
  ubuntu: "ubuntu/21.04/cloud"
  debian: "debian/10/cloud"
  centos: "centos/8/cloud"

container_os_image: "{{ container_os_images[guest_os_distro] }}"

#######
# LXD #
#######
lxd_socket_path: /var/snap/lxd/common/lxd/unix.socket
lxd_url: "unix:{{ lxd_socket_path }}"
lxd_snap_url: "{{ lxd_url }}"
lxd_image_url: "https://images.linuxcontainers.org"
