---
- name: "set bridge config"
  hosts: "*"
  gather_facts: false
  become: true
  vars:
    br_intfs:
      - br_name: "multus_br2"
        intf_name: "eth2"
      - br_name: "multus_br3"
        intf_name: "eth3"
  tasks:
    - name: "create network /etc/network/interfaces.d/{{ item.br_name }} file"
      template:
        src: "templates/bridge_interface.j2"
        dest: "/etc/network/interfaces.d/{{ item.br_name }}"
      loop: "{{ br_intfs }}"

    - name: "modify /etc/network/interfaces"
      replace:
        path: "/etc/network/interfaces"
        regexp: '^(\S+) {{ item.intf_name }}(.*)$'
        replace: '#\1 {{ item.intf_name }}\2'
      loop: "{{ br_intfs }}"

    - name: "modify /etc/network/interfaces.d/50-cloud-init"
      replace:
        path: "/etc/network/interfaces.d/50-cloud-init"
        regexp: '^(\S+) {{ item.intf_name }}(.*)$'
        replace: '#\1 {{ item.intf_name }}\2'
      loop: "{{ br_intfs }}"

    - name: "Delete IPs from {{ item.intf_name }}"
      ansible.builtin.command: "ip addr flush dev {{ item.intf_name }}"
      loop: "{{ br_intfs }}"

    - name: restart networking service
      systemd:
        name: "networking"
        enabled: true
        state: restarted
