---
###########
# Globals #
###########
libvirt_dir: "/var/lib/libvirt/images"

cloud_init_disk: "vdz"
vm_volumes_fs_format: "ext4"

#############
# OS images #
#############
vm_os_images:
  ubuntu: "ubuntu-16.04-server-cloudimg-amd64-disk1.img"
  debian: "debian-10-openstack-amd64.qcow2"
  fcos: "fedora-coreos-32.qcow2"
  flatcar: "flatcar-linux1.qcow2"
  centos: "CentOS-8-GenericCloud-8.3.2011-20201204.2.x86_64.qcow2"

vm_os_image: "{{ vm_os_images[guest_os_distro] }}"

destroy_images: False
