---
###########
# Globals #
###########
#libvirt_dir: "/var/lib/libvirt/images"
libvirt_dir: "/libvirt/images"
libvirt_url: qemu:///system
libvirt_security_driver: none
libvirt_default_mtu: 9000

destroy_images: False
rename_net_interface: False
cloud_init_disk: "vdz"

########
# VBMC #
########
# Virtual BMC is enabled by default
vbmc: True

# By default we install with pip, but if you prefer to do it manually, set this to false
vbmc_pip: True

# Default vbmc service, override if something else on your distro
vbmc_service: vbmcd

# Default vbmc starting port 623
vbmc_port: 623

#############
# OS images #
#############
guest_os_images:
  ubuntu: "ubuntu-16.04-server-cloudimg-amd64-disk1.img"
  #debian: "debian-10-openstack-amd64.qcow2"
  debian: "debian-11-generic-amd64.qcow2"
  fcos: "fedora-coreos-32.qcow2"
  flatcar: "flatcar-linux1.qcow2"
  # centos: "CentOS-8-GenericCloud-8.2.2004-20200611.2.x86_64.qcow2"
  # centos-7: "CentOS-7-x86_64-GenericCloud-2009.qcow2"
  # centos-8.2: "CentOS-8-GenericCloud-8.2.2004-20200611.2.x86_64.qcow2"
  #  centos: "CentOS-8-GenericCloud-8.3.2011-20201204.2.x86_64.qcow2"
  centos: "CentOS-Stream-GenericCloud-8-20220125.1.x86_64.qcow2"
guest_os_image: "{{ vm_os_images[guest_os_distro] }}"
