---
####################
# Host OS variables
####################
node_prefix: ""

# Cluster sizing info
#####################
master_nb: 1
master_ram: 4
master_cpu: 1

worker_nb: 2
worker_ram: 4
worker_cpu: 1

# Networking info
#################
host_interfaces:
  - name: overlay-br
    mode: dhcp
    cidr: 10.150.150.0/24
    bridge: overlay-br
  - name: ext-br
    forward: nat
    mode: dhcp
    cidr: 10.100.100.0/24
    bridge: ext-br
    pxe: True

dns_domain: "mydomain.org"

# Storage info
##############
root_disk_size: "20"

storage_volume_enabled: False
virt_volume_group: "virtvg"

host_volumes:
  - name: volume1
    size: 10
    format: raw
  - name: volume2
    size: 10
    format: raw
  - name: volume3
    size: 10
    format: raw
