---
###########
# Globals #
###########
# libvirt_dir: "/var/lib/libvirt/images"
libvirt_dir: "/libvirt/images"
libvirt_url: qemu:///system
libvirt_security_driver: none
libvirt_default_mtu: 9000

destroy_images: false
rename_net_interface: false
cloud_init_disk: "vdz"

#########
# Guest #
#########
guest_timezone: "UTC"
qemu_guest_agent_enabled: true

########
# VBMC #
########
# Virtual BMC is disabled by default
vbmc: false

# By default we install with pip, but if you prefer to do it manually
# set this to false
vbmc_pip: true

# Default vbmc service, override if something else on your distro
vbmc_service: vbmcd

# Default vbmc starting port 623
vbmc_port: 623

#############
# OS images #
#############
guest_os_images:
  # ubuntu: "ubuntu-16.04-server-cloudimg-amd64-disk1.img"
  ubuntu: "focal-server-cloudimg-amd64-disk-kvm.img"
  # debian: "debian-10-openstack-amd64.qcow2"
  debian: "debian-11-generic-amd64.qcow2"
  fcos: "fedora-coreos-32.qcow2"
  flatcar: "flatcar-linux1.qcow2"
  #  centos: "Rocky-8-GenericCloud-8.4-20210620.0.x86_64.qcow2"
  centos: "Rocky-8-GenericCloud-8.6.20220702.0.x86_64.qcow2"
