---
###########
# Globals #
###########
libvirt_dir: "/var/lib/libvirt/images"

cloud_init_disk: "vdb"

#####################
# Docker containers #
#####################
docker_registry_name: "registry"
docker_registry_image: "registry:2"

docker_pip_cache_name: "devpi_proxy"
docker_pip_cache_image: "127.0.0.1:5000/devpi"

docker_apt_cache_name: "apt-cacher-ng_proxy"
docker_apt_cache_image: "127.0.0.1:5000/apt-cacher-ng"

docker_dns_server_name: "docker-dnsmasq"
docker_dns_server_image: "127.0.0.1:5000/docker-dnsmasq"

############
# Packages #
############
yum_dependencies:
  - libvirt
  - libvirt-devel
  - bridge-utils
  - genisoimage
  - qemu-kvm
  - rsync

# ImportError: No module named ssl_match_hostname'
#  - remove python-configparser
apt_dependencies:
  - openssh-server
  - libvirt-daemon-system
  - bridge-utils
  - genisoimage
  - qemu-kvm
  - rsync

pip_dependencies:
  - docker
  - pip
  - requests
  - libvirt-python
  - netaddr
  - lxml

#############
# OS images #
#############
vm_os_images:
  ubuntu: "ubuntu-16.04-server-cloudimg-amd64-disk1.img"
  debian: "debian-10-openstack-amd64.qcow2"
  fcos: "fedora-coreos-32.qcow2"
  centos: "CentOS-8-GenericCloud-8.2.2004-20200611.2.x86_64.qcow2"

vm_os_image: "{{ vm_os_images[guest_os_distro] }}"

destroy_images: False
