---
- name: Install CentOS packages
  become: true
  yum:
    name: "{{ yum_dependencies }}"
  when: ansible_distribution|lower == "centos"

- name: Install Ubuntu packages
  become: true
  apt:
    pkg: "{{ apt_dependencies }}"
  when: ansible_distribution|lower in ["ubuntu", "debian"]

# - import_tasks: docker/enable_docker.yml
#   become: true
#   when: docker_enabled | bool

- name: Install/Update pip packages
  become: true
  pip:
    name: "{{ pip_dependencies }}"
    state: latest

- import_tasks: docker/enable_registry.yml
  when: registry_enabled | bool

- name: Starting Libvirtd service
  become: true
  service:
    name: "libvirtd"
    state: started
    enabled: true

- import_tasks: docker/enable_apt_proxy.yml
  when: apt_cache_enabled | bool
