---
- import_tasks: docker/disable_registry.yml
  when: destroy_docker_registry | bool

- import_tasks: docker/disable_apt_proxy.yml
  when: apt_cache_enabled | bool and destroy_apt_cache | bool

- import_tasks: docker/disable_dns_server.yml
  when: dns_server_enabled | bool and destroy_dns_server | bool
