---
- name: Load cluster_nodes variables
  set_fact:
    cluster_nodes: "{{ lookup('template','nodes.j2') | from_yaml }}"
  tags: network

- name: "Copy cluster_nodes in {{ tmp_dir }}/{{ group }}"
  blockinfile:
    path: "{{ tmp_dir }}/{{ group }}/cluster_nodes"
    create: true
    block: |
        {{ cluster_nodes | to_nice_json(indent=2) }}
  tags: network

- name: "Display cluster_nodes"
  debug:
    msg: "{{ cluster_nodes | to_nice_yaml(indent=2) }}"
  tags: network
