---
- name: Set nodes_interfaces
  ansible.builtin.set_fact:
    nodes_interfaces: "{{ nodes | map(attribute='net_intfs') | flatten | json_query('[*].name') }}"

- name: Set network_names
  ansible.builtin.set_fact:
    network_names: "{{ networks | map(attribute='name') | list }}"

- name: "[KVM host] Check network interfaces naming"
  ansible.builtin.fail:
    msg: "Network interface {{ item }} not in {{ network_names }}"
  when: item not in network_names
  loop: "{{ nodes_interfaces }}"
