---
- name: Check storage variables
  block:
    - name: "[KVM host] Set lvm_storage"
      ansible.builtin.set_fact:
        lvm_storage: "{{ vm_volumes is defined and vm_volumes|length > 0 and 'raw' in vm_volumes|map(attribute='format')|list }}"

    - name: "[KVM host] Check physical_disks is set"
      ansible.builtin.fail:
        msg: "when one vm_volumes is set to 'raw', physical_disks MUST be set"
      when:
        - lvm_storage
        - physical_disks is not defined

    - name: "[KVM host] Check virt_volume_group is set"
      ansible.builtin.fail:
        msg: "when one vm_volumes is set to 'raw', virt_volume_group MUST be set"
      when: lvm_storage and virt_volume_group is not defined

    - name: "[KVM host] Check vm_volumes_mount_path is set"
      ansible.builtin.fail:
        msg: "when vm_volumes_mount is set to true, vm_volumes_mount_path MUST be set"
      when:
        - vm_volumes_mount is defined
        - vm_volumes_mount
        - vm_volumes_mount_path is not defined

- name: Check LVM storage is available
  block:
    - name: "[KVM host] List storage pool"
      community.libvirt.virt_pool:
        command: list_pools
      register: pool_exists

    - name: "[KVM host] Define {{ virt_volume_group }} storage pool"
      become: true
      community.libvirt.virt_pool:
        command: define
        name: "{{ virt_volume_group }}"
        xml: "{{ lookup('template', 'libvirt/pool.xml.j2') }}"
      when: virt_volume_group not in pool_exists.list_pools

    - name: "[KVM host] Copy Libvirt XML pool domain in {{ tmp_dir }}/pool.xml"
      ansible.builtin.blockinfile:
        path: "{{ tmp_dir }}/pool.xml"
        create: true
        block: |
            {{ lookup('template', 'libvirt/pool.xml.j2') }}

    - name: "[KVM host] Start {{ virt_volume_group }} storage pool"
      become: true
      community.libvirt.virt_pool:
        command: create
        name: "{{ virt_volume_group }}"

      when: virt_volume_group not in pool_exists.list_pools

    - name: "[KVM host] Autostart {{ virt_volume_group }} storage pool"
      become: true
      community.libvirt.virt_pool:
        autostart: true
        name: "{{ virt_volume_group }}"
  when: lvm_storage
