---
- name: Create virtual volumes
  virt_volume:
    name: "{{ item.1.name }}"
    capacity: "{{ item.1.size }}G"
    pool: "{{ virt_volume_group }}"
    format: "{{ item.1.format | default('raw') }}"
    state: present
  with_subelements:
    - "{{ cluster_nodes }}"
    - disks
  when: item.1.type == 'raw'

- name: Create QCOW2 disk
  command: "qemu-img create -o preallocation=metadata -f qcow2 {{ tmp_dir }}/{{ group }}/{{ item.0.name }}/{{ item.1.name }}.qcow2 {{ item.1.size }}G"
  args:
    creates: "{{ tmp_dir }}/{{ group }}/{{ item.0.name }}/{{ item.1.name }}.qcow2"
  with_subelements:
    - "{{ cluster_nodes }}"
    - disks
  when: item.1.type == 'qcow2'
