---
- name: Destroy virtual volumes
  virt_volume:
    name: "{{ item.1.name }}"
    pool: "{{ virt_volume_group }}"
    state: absent
  with_subelements:
    - "{{ cluster_nodes }}"
    - disks
  when: item.1.type == 'raw'

- name: Delete QCOW2 disk
  file:
    path: "{{ tmp_dir }}/{{ item.0.name }}/{{ item.1.name }}.qcow2"
    state: absent
  with_subelements:
    - "{{ cluster_nodes }}"
    - disks
  when: item.1.type == 'qcow2'
