---
- name: List virtual networks
  community.libvirt.virt_net:
    command: list_nets
  register: net_exists

- name: Collect facts about existing Libvirt networks
  community.libvirt.virt_net:
    command: facts

- name: Copy Libvirt XML network domain in {{ tmp_dir }}/{{ group }}
  blockinfile:
    path: "{{ tmp_dir }}/{{ group }}/{{ item.name }}.xml"
    create: true
    block: |
        {{ lookup('template', 'network.xml.j2') }}
  with_items: "{{ cluster_networks }}"

- name: Steps to setup networks using Libvirt
  block:
    - name: Define virtual networks
      community.libvirt.virt_net:
        command: define
        name: "{{ item.name }}"
        xml: '{{ lookup("template", "network.xml.j2") }}'
      with_items: "{{ cluster_networks }}"

    - name: Start virtual networks
      community.libvirt.virt_net:
        state: active
        autostart: true
        name: "{{ item.name }}"
      with_items: "{{ cluster_networks }}"
  when: (item.name not in ansible_libvirt_networks) or (item.name in ansible_libvirt_networks and ansible_libvirt_networks[item.name].state == 'inactive')
