---
- name: List virtual networks
  virt_net:
    command: list_nets
  register: net_exists

- name: Collect facts about existing Libvirt networks
  virt_net:
    command: facts

- name: "Copy networks in {{ tmp_dir }}"
  blockinfile:
    path: "{{ tmp_dir }}/networks"
    create: true
    block: |
        {{ networks | to_nice_json(indent=2) }}

- name: Steps to setup network using Libvirt
  block:
    - name: "Copy Libvirt XML network domain in {{ tmp_dir }}"
      blockinfile:
        path: "{{ tmp_dir }}/{{ item.name }}.xml"
        create: true
        block: |
            {{ lookup('template', 'network.xml.j2') }}
      with_items: "{{ networks }}"
    - name: Define virtual networks
      virt_net:
        command: define
        name: "{{ item.name }}"
        xml: '{{ lookup("template", "network.xml.j2") }}'
      with_items: "{{ networks }}"
    # - name: Autostart virtual networks
    #   virt_net:
    #     autostart: true
    #     name: "{{ item.name }}"
    #   with_items: "{{ networks }}"
    - name: Start virtual networks
      virt_net:
        state: active
        autostart: true
        name: "{{ item.name }}"
      with_items: "{{ networks }}"
  when: (item.name not in ansible_libvirt_networks) or (item.name in ansible_libvirt_networks and ansible_libvirt_networks[item.name].state == 'inactive')
