---
- name: Create virtual volumes
  virt_volume:
    name: "{{ item.1.name }}"
    capacity: "{{ item.1.size }}G"
    pool: "{{ virt_volume_group }}"
    format: "{{ item.1.format | default('raw') }}"
    state: present
  with_subelements:
    - "{{ cluster_nodes }}"
    - disks
